name: Compare Performance with Master
on:
  pull_request:
    branches:
      - lebrice/temp_master  # TEMP: Change to `master` before merging.

jobs:
  benchmark:
    name: Run pytest-benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[all]

      - name: Unit tests with Pytest
        run: |
          pytest --benchmark-only --benchmark-json=benchmark_results.json

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ github.token }}
          workflow: upload.yml
          name: benchmark_results
          path: old_benchmark
          commit: ${{github.event.pull_request.base.sha}}
        continue-on-error: true

      - name: Run the action
        uses: nils-braun/pytest-benchmark-commenter@v2
        with:
          comparison-benchmark-file: "old_benchmark/benchmark_results.json"